cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('', views.CartView.as_view(), name='summary'),
    path('increase_quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease_quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('delivery/', views.DeliveryView.as_view(), name='delivery'),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import core.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('accounts/', include('allauth.urls')),
    path('staff/', include('staff.urls', namespace='staff')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('product-list/', views.ProductListView.as_view(), name='product-list'),
    path('product-create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product/<pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),

]

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms

from cart.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price',
            'primary_category',
            'available_colours',
            'available_sizes',

        ]

staff/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic

from cart.models import Order, Product
from staff.forms import ProductForm
from staff.mixins import StaffUserMixin


# Create your views here.
class StaffView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered=True).order_by('-ordered_date')
    paginate_by = 20
    context_object_name = 'orders'


class ProductListView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 20
    context_object_name = 'products'


class ProductDeleteView(LoginRequiredMixin, StaffUserMixin, generic.DeleteView):
    template_name = 'staff/product_delete.html'

    def get_queryset(self):
        queryset = Product.objects.all()
        return queryset

    def get_success_url(self):
        return reverse('staff:product-list')


class ProductUpdateView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/product_update.html'
    form_class = ProductForm

    def get_queryset(self):
        queryset = Product.objects.all()
        return queryset

    def form_valid(self, form):
        form.save()
        return super(ProductUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('staff:product-list')


class ProductCreateView(LoginRequiredMixin, StaffUserMixin, generic.CreateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse('staff:product-list')

    def form_valid(self, form):
        form.save()
        print(form.cleaned_data['title'])
        return super(ProductCreateView, self).form_valid(form)

templates/staff/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-12">
               <div>
                   <a href="{% url 'staff:product-list' %}">Wróć do listy produktów</a>
                   <hr/>
                   <h1>Dodaj produkt</h1>
               </div>
               <form method="POST" enctype="multipart/form-data">
                   {% csrf_token %}
                   {{ form|crispy }}
                   <button type="submit" class="btn btn-primary">Potwierdź</button>
               </form>

           </div>
       </div>
   </div>
</div>

{% endblock content %}

templates/staff/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-12">
               <div>
                   <h1>Delete the product</h1>
               </div>
               <form method="POST">
                   {% csrf_token %}
                   {{ form|crispy }}
                   <button type="submit" class="btn btn-primary">Submit</button>
               </form>

           </div>
       </div>
   </div>
</div>

{% endblock content %}

templates/staff/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-12">
               <h2 class="text-black">Portal Pracowniczy</h2>
               <a href="{% url 'staff:product-create' %}">Dodaj nowy produkt</a>
               <div class="card">
                   <div class="card-body">
                       <a href="{% url 'staff:staff' %}">Zamówienia</a>
                       <hr />
                       <h5 class="card-title">Produkty</h5>
                       <div class="site-blocks-table">
                           <table class="table">
                               <thead>
                                   <tr>
                                       <th>Nazwa</th>
                                       <th>Cena</th>
                                       <th>Akcje</th>
                                       <th>Status produktu</th>
                                   </tr>
                               </thead>
                               <tbody>
                                   {% for product in products %}
                                   <tr>
                                       <td>{{ product.title }}</td>
                                       <td>{{ product.get_price }} zł</td>
                                       <td>
                                           <a href="{{ product.get_update_url }}">Aktualizuj</a>
                                           <a
                                              tabindex="0"
                                              class="btn btn-sm btn-primary"
                                              role="button"
                                              data-html="true"
                                              data-toggle="popover"
                                              data-trigger="focus"
                                              title="Are you sure you want to delete this product?"
                                              data-content="<a href='{{ product.get_delete_url }}'>Confirm</a>"
                                           >X</a>
                                       </td>
                                       <td>{% if product.active %}Aktywny{% else %}Nieaktywny{% endif %}</td>
                                   </tr>
                                   {% empty %}
                                   <tr>
                                       <td colspan="4">Brak produktów</td>
                                   </tr>
                                   {% endfor %}
                               </tbody>
                           </table>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>

{% endblock content %}

{% block scripts %}


{% comment %} PO KLIKNIECIU WYSKAKUJE POPOVER {% endcomment %}
<script>
   $(function () {
       $("[data-toggle=popover]").popover();
   });
</script>

{% endblock scripts %}

templates/staff/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-12">
               <div>
                   <a href="{% url 'staff:product-list' %}">Go back to products</a>
                   <hr/>
                   <h1>Update the product</h1>
               </div>
               <form method="POST" enctype="multipart/form-data">
                   {% csrf_token %}
                   {{ form|crispy }}
                   <button type="submit" class="btn btn-primary">Submit</button>
               </form>

           </div>
       </div>
   </div>
</div>

{% endblock content %}

templates/staff/staff.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-12">
               <h2 class="text-black">Portal Pracowniczy</h2>
               <div class="card">
                   <div class="card-body">
                       <a href="{% url 'staff:product-list' %}">Produkty</a>
                       <hr />
                       <h5 class="card-title">Ostatnie zamówienia</h5>
                       <div class="site-blocks-table">
                           <table class="table">
                               <thead>
                                   <tr>
                                       <th>Nr</th>
                                       <th>Data zamówienia</th>
                                       <th>Użytkownik</th>
                                       <th>Suma</th>
                                       <th>Status płatności</th>
                                   </tr>
                               </thead>
                               <tbody>
                                   {% for order in orders %}
                                   <tr>
                                       <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                       <td>{{ order.ordered_date }}</td>
                                       <td>{{ order.user.email }}</td>
                                       <td>{{ order.get_total }} zł</td>
                                       <td>{% if order.ordered %}Zapłacone{% else %}Niezapłacone{% endif %}</td>
                                   </tr>
                                   {% empty %}
                                   <tr>
                                       <td colspan="4">Brak zamówień</td>
                                   </tr>
                                   {% endfor %}
                               </tbody>
                           </table>
                       </div>
                       {% if page_obj.has_other_pages %}
                       <div class="row">
                           <div class="col-md-12 text-center">
                               <div class="site-block-27">
                                   <ul>
                                       {% if page_obj.has_previous %}
                                       <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                       {% else %}
                                       <li class="disabled"><span>&laquo;</span></li>
                                       {% endif %}

                                       {% for i in paginator.page_range %}
                                           {% if page_obj.number == i %}
                                               <li class="active">
                                                   <span>
                                                       {{ i }}
                                                       <span class="sr-only">(current)</span>
                                                   </span>
                                               </li>
                                           {% else %}
                                               <li><a href="?page={{ i }}">{{ i }}</a></li>
                                           {% endif %}
                                       {% endfor %}

                                       {% if page_obj.has_next %}
                                       <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                       {% else %}
                                       <li class="disabled"><span>&raquo;</span></li>
                                       {% endif %}
                                   </ul>
                               </div>
                           </div>
                       </div>
                       {% endif %}
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>

{% endblock content %}