cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('', views.CartView.as_view(), name='summary'),
    path('increase_quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease_quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('delivery/', views.DeliveryView.as_view(), name='delivery'),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import core.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('accounts/', include('allauth.urls')),
    path('staff/', include('staff.urls', namespace='staff')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('product-list/', views.ProductListView.as_view(), name='product-list'),
    path('product-create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product/<pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),

]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="pl-PL">
<head>
   <title> {% block head_title %}Sklep Magic Knots{% endblock %}</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


   <meta name="msapplication-TileColor" content="#ffffff">
   <meta name="theme-color" content="#ffffff">

   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
   <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/aos.css' %}">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
         integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body >

<div class="site-wrap" >
   <header class="site-navbar" role="banner">
       <div class="site-navbar-top">
           <div class="container">
               <div class="row align-items-center">
                   <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                       <div>
                           <a href="/">
                               <img class="img-fluid" src="{% static 'images/magic2.png' %}" style="max-width: 250px;"/>
                           </a>
                       </div>
                   </div>

                   <div class="col-6 col-md-4 order-3 order-md-3 text-right" >
                       <div class="site-top-icons">
                           <ul>
                               <li>
                                   {% if request.user.is_authenticated %}
                                       <a href="{% url 'account_logout' %}"><span>Wyloguj się <i class="fas fa-sign-out-alt"></i></span></a>
                                       <a href="{% url 'profile' %}"><span>Konto <i class="fas fa-user"></i></span></a>

                                   {% else %}
                                       <a href="{% url 'account_login' %}"><span>Zaloguj się <i
                                               class="fas fa-sign-in-alt"></i></span></a>
                                    <a href="{% url 'account_signup' %}"><span>Zarejestruj się <i
                                               class="fas fa-sign-in-alt"></i></span></a>

                                   {% endif %}
                               </li>
                               <li>
                                   <a href="{% url 'cart:summary' %}" class="site-cart">
                                       <span><i class="fas fa-shopping-cart"></i></span>
                                                Koszyk
                                       <span class="count">{{ request|cart_item_count }}</span>

                                   </a>

                               </li>
                               <li class="d-inline-block d-md-none ml-md-0">
                                   <a href="/" class="site-menu-toggle js-menu-toggle">
                                       <span><i class="fas fa-bars"></i></span>
                                   </a>
                               </li>
                           </ul>
                       </div>
                   </div>

               </div>
           </div>
       </div>
       {% include 'navbar.html' %}
       {% if messages %}
           {% for message in messages %}
               <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                   <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                   <span class="alert-inner--text">{{ message }}</span>
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                   </button>
               </div>
           {% endfor %}
       {% endif %}

   </header>

   {% block content %}
   {% endblock content %}

   {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}

{% block scripts %}


{% endblock scripts %}

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="bg-light py-3">
   <div class="container">
       <div class="row">
           <div class="col-md-12 mb-0">
               <a href="{% url 'home' %}">Strona główna</a>
               <span class="mx-2 mb-0">/</span>
               <strong class="text-black">Kontakt</strong>
           </div>
       </div>
   </div>
</div>

<div class="site-section">
   <div class="container">
       <div class="row justify-content-center">
           <div class="col-md-7">
               <h2 class="h3 mb-3 text-black">Skontaktuj się</h2>
           </div>
           <div class="col-md-7">
               <form method="POST">
                   {% csrf_token %}
                   {{ form|crispy }}
                   <input type="submit" class="btn btn-primary btn-lg btn-block" value="Wyślij wiadomość">
               </form>
           </div>
       </div>
   </div>
</div>

{% endblock content %}

templates/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="fas fa-heart"></i>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 pt-5 pt-md-0">
            </div>
        </div>
    </div>
</div>

<div class="site-section" >
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Magic Knots</h2>
            </div>
            <div class="col-md-7">
                <h5 class="h5 mb-3 text-black">
                    Odkryj magię ręcznie wykonanych makram!
                    Zapraszamy Cię do podróży w świat delikatnych węzłów,
                    kunsztownych wzorów i naturalnych materiałów.
                    Oferujemy szeroki wybór unikalnych wzorów i stylów,
                    które zaspokoją różnorodne gusta i preferencje.
                    Bez względu na to, czy szukasz pięknego wiszącego dekoru do swojego wnętrza,
                    oryginalnej biżuterii czy unikatowego prezentu dla bliskiej osoby,
                    mamy coś specjalnego dla Ciebie.
                    Nasza pasja do tworzenia makramy wynika z pragnienia wprowadzenia piękna do Twojego życia.
                    Chcemy, aby nasze dzieła wzbogacały przestrzeń,
                    w której się znajdują, i dodawały wyjątkowego charakteru każdemu wnętrzu.
                    Makramy są nie tylko ozdobą, ale także wyrazem Twojego indywidualnego stylu.
                    Ponadto, oferujemy również możliwość zamówienia spersonalizowanych makram.
                    Tworzymy dla Ciebie niepowtarzalne dzieła, które odzwierciedlają Twoją wyjątkowość.
                    Zamów już dziś nasz ręcznie wykonany makram i dostrzeż różnicę, jaką może przynieść do Twojego życia.
                    Dołącz do nas i pozwól nam dodać nutę wyjątkowości do Twojego otoczenia.
                </h5>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/navbar.html
{% load static %}

<nav class="site-navigation text-right text-md-center" role="navigation" style="background-image: url({% static 'images/the_background.jpg' %});">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/" ><h2 class="h3 text-black">Strona główna</h2></a></li>
            <li><a href="{% url 'cart:product-list' %}"><h2 class="h3 text-black" >Sklep</h2></a></li>
            <li><a href="{% url 'contact' %}"><h2 class="h3 text-black">Kontakt</h2></a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff' %}"><h2 class="h3 text-black">Staff</h2></a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Twój profil</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                            <a href="{% url 'account_logout' %}">
                                <small class="float-right">Wyloguj się</small></a>
                        </h5>
                        <hr />
                        <h5 class="card-title">
                            <a href="{% url 'account_change_password' %}">Zmień hasło</a>
                        </h5>
                        <hr />
                        <h5 class="card-title">
                            <a href="{% url 'account_email' %}">Zmień email</a>
                        </h5>
                        <hr />
                        <h5 class="card-title">Twoje zamówienia</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Nr zamówienia</th>
                                        <th>Data</th>
                                        <th>Suma</th>
                                        <th>Status płatności</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Zapłacone{% else %}Niezapłacone{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">Nie masz jeszcze żadnych zamówień.</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>